serenity {
  project.name = "AUTO_FRONT_POM_FACTORY"
  take.screenshots = AFTER_EACH_STEP
}

webdriver {
  base.url = "http://localhost:3001/"
  driver = chrome
  autodownload = true
  capabilities.acceptInsecureCerts = true
  capabilities {
    browserName = "chrome"
    "goog:chromeOptions" {
      args = [
        "--no-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--window-size=683,768",
        "--allow-insecure-localhost",
        "--ignore-certificate-errors",
        "--unsafely-treat-insecure-origin-as-secure=http://localhost:3001"
      ]
    }
  }
}

environments {
  default {
    webdriver.base.url = "http://localhost:3001/"
  }
}
